[package]
name = "replicate-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "*"
lazy_static = "1.4.0"
isahc = "1.7.2"
serde = {version = "1.0.193", features = ["derive"]}
serde_json = "1.0"
erased-serde = "*"
